Initial commit of the Virtual Pointer
Ruyk/computecpp-sdk pull request #5
Opened 2017-05-05 10:34 UTC by Ruyk

This initial commit implements the basic structure of the virtual
pointer interface for buffers, that enables allocation of deallocation
of pointer-like structures that are not dereferenciable on the host
but can be used to retrieve buffers and offsets later on.
PointerMapper is a normal object, unlike the singleton implemented for
the legacy pointer interface.
See README.adoc for details.

2017-05-08 10:01 UTC, ProGTX commented on utils/vptr/README.adoc
> +space is non-dereferenciable on the host, but accessors can be obtained
non-dereferenciable -> non-dereferenceable

2017-05-08 10:01 UTC, ProGTX commented on utils/vptr/README.adoc
> +This differes from the legacy_pointer interface in that a contiguous
differes -> differs

2017-05-08 10:02 UTC, ProGTX commented on utils/vptr/README.adoc
> +In situations where developers needs complete addressing of the entire
needs -> need

2017-05-08 10:17 UTC, ProGTX commented on utils/vptr/README.adoc
> +Note that the pointer is non-dereferenciable on the host, but host accessors
non-dereferenciable -> non-dereferenceable

2017-05-08 10:18 UTC, ProGTX commented on utils/vptr/README.adoc
> +*codeplay::PointerMapper::get_offset* function.
What offset is this?

2017-05-08 10:25 UTC, ProGTX commented on utils/vptr/include/pointer_alias.hpp
> +              ((&(*acc.get_pointer())));
Why the need for `&(*())` and the `retinterpret_cast`? Per the spec `acc.get_pointer()` should return `global_ptr` "when access target is global_buffer and access mode is non-atomic"

2017-05-08 10:25 UTC, ProGTX commented on utils/vptr/include/pointer_alias.hpp
> +     return reinterpret_cast<T *>((&(*acc.get_pointer())));
Similar to above

2017-05-08 10:26 UTC, ProGTX commented on utils/vptr/include/virtual_ptr.hpp
> +#define VIRTUAL_PTR_VERBOSE 0
This could have an `#ifndef VIRTUAL_PTR_VERBOSE`

2017-05-09 11:01 UTC, Ruyk commented on utils/vptr/README.adoc
> +*codeplay::PointerMapper::get_offset* function.
This is the offset from the base of the SYCL buffer to the actual address of the pointer given by the user. I'll describe the virtual pointer a little bit better so this is clearer.

2017-05-09 11:10 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +#define VIRTUAL_PTR_VERBOSE 0
Good point.

2017-05-10 00:04 UTC, AerialMantis requested changes
Looks good, i've added some comments; mostly wording fixes and clarifications. I think the README could do with some further further explanation as to the use case for this functionality.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +pointer that facilitates a pointer interface for SYCL buffers.
"pointer" -> "raw pointer" ?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +This differs from the legacy_pointer interface in that a contiguous
Is the virtual pointer interface intended as  a replacement for the legacy pointer interface?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +The pointer can be offseted, so that positions inside a given buffer
"offseted" -> "offset".

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +When allocating a buffer using *SYCLMalloc*, a virtual address in the
"SYCLMalloc" -> "SYCLmalloc".

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/pointer_alias.hpp
> +              ((&(*acc.get_pointer())));
I believe this is because the accessors constructed from a `virtual_ptr` are always from a `buffer` of `uint8_t` type, which means the resulting `global_ptr<uint8_t>` has be aliased into a `global_ptr<T>`, if this is the case we should have a comment describing this as it could be confusing as to it's purpose.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/pointer_alias.hpp
> +template<typename T, typename AccessorT>
I think this template is too permissive, it will allow a user to pass a parameter of any type, which could cause particular problems if a user were to attempt to use this with a different kind of accessor, something like this would restrict the interface to the case which we want to support:

```
template<typename T, typename dataT, int kDims, cl::sycl::access::mode accessMode>
cl::sycl::global_ptr<T> get_device_ptr_as(cl::sycl::accessor<dataT, kDims, accessMode, cl::sycl::access::target::global_buffer>& acc)
```

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/pointer_alias.hpp
> +     return reinterpret_cast<T *>((&(*acc.get_pointer())));
Same as above.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +class PointerMapper {
Could we make this "pointer_mapper" ?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +  /* Fake Pointers are implemented using an ADDRESS_BIT
This mentions a fake pointer, should this be virtual pointer?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +  struct pMapNode_t {
Could we make this "p_map_node_t" ?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +   * A pointer is nullptr if the value is of null_virtual_ptr
It looks like `null_virtual_ptr` is not used here.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +   * Adds a pointer to the map and returns the fake pointer id.
"fake pointer" -> "virtual pointer" ?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +float * a = static_cast<float *>(SYCLmalloc(10 * sizeof(float)), pMap);
I think this is a typo, should this be `float * a = static_cast<float *>(SYCLmalloc(10 * sizeof(float), pMap));`instead?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/README.adoc
> +int * b = static_cast<int *>(SYCLmalloc(25 * sizeof(int)), pMap);
Same as above.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/tests/basic.cc
> +      h.single_task<class foo1>([=]() { accB[0] = 1.0f; });
There is an implicit conversion here, `1.0f` is being converted to `int8_t` the type of the `buffer`.

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/tests/basic.cc
> +#ifdef __COMPUTECPP__
We don't really want to expose the implementation details, could this check be done with OpenCL interop instead?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/tests/basic.cc
> +        std::cout << "Error " << std::endl;
Should this also output `e.what()` ?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/tests/offset.cc
> +    size_t offset = pMap.get_offset(myPtr);
Can the `PointerMapper` provide any protections against buffer overflow? It appears that if a user were to offset a the virtual pointer, beyond it's allocation it could provide access to neighboring buffer objects in the pointer map.

```
float *ptrA = static_cast<float *>(SYCLmalloc(10 * sizeof(float), pMap));
float *ptrB = static_cast<float *>(SYCLmalloc(10 * sizeof(float), pMap));

ptrA += some_value_greater_than_10;

buffer_t bA = pMap.get_buffer(ptrA);
buffer_t bB = pMap.get_buffer(ptrB);

(bA == bB) // pointers could return the same buffer object
(pMap.get_offset(ptrA) == pMap.get_offset(ptrA)) // pointers could return the same offsets
```

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +  static const unsigned long ADDRESS_BITS = sizeof(void *) * 8;
Does this technique also work on 32bit systems?

2017-05-10 00:04 UTC, AerialMantis commented on utils/vptr/include/virtual_ptr.hpp
> +  virtual_pointer_t add_pointer(buffer_t &&b) {
Are these member functions thread safe?

2017-06-07 17:37 UTC, Ruyk commented on utils/vptr/README.adoc
> +This differs from the legacy_pointer interface in that a contiguous
It is an alternative implementation, a little bit more complicated but with less limitations in terms of indexing.

2017-06-19 12:27 UTC, Ruyk commented on utils/vptr/include/pointer_alias.hpp
> +              ((&(*acc.get_pointer())));
This is not required in recent versions of ComputeCpp

2017-06-19 12:28 UTC, Ruyk commented on utils/vptr/include/pointer_alias.hpp
> +     return reinterpret_cast<T *>((&(*acc.get_pointer())));
Not required anymore

2017-06-19 12:32 UTC, Ruyk commented on utils/vptr/include/pointer_alias.hpp
> +template<typename T, typename AccessorT>
This can be used for local as well, so I don't think we should restrict it that much

2017-06-19 12:34 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +class PointerMapper {
This is already used as "PointerMapper" in other projects

2017-06-19 12:35 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +  /* Fake Pointers are implemented using an ADDRESS_BIT
Removed

2017-06-19 12:35 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +   * A pointer is nullptr if the value is of null_virtual_ptr
It can be used by external users

2017-06-19 12:35 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +  struct pMapNode_t {
too long!

2017-06-19 12:36 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +  virtual_pointer_t add_pointer(buffer_t &&b) {
No, it is the user responsibility to access in a thread safe manner

2017-06-19 12:36 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +   * Adds a pointer to the map and returns the fake pointer id.
fixed

2017-06-19 12:37 UTC, Ruyk commented on utils/vptr/tests/basic.cc
> +        std::cout << "Error " << std::endl;
That would require try/catch and rethrow, which cannot be enabled in projects with -fnoexceptions

2017-06-19 14:45 UTC, AerialMantis commented on utils/vptr/README.adoc
> +This differs from the legacy_pointer interface in that a contiguous
Are we keeping the legacy pointer as well?

2017-07-06 14:42 UTC, merged