Task/11355 & task/11592: Add PointerMapper to the scheduler & remove template parameter from the PointerMapper
Ruyk/computecpp-sdk pull request #6
Opened 2017-06-15 16:10 UTC by wyaneva

This merge request relates to tasks 11355 and 11592.

We need to add a PointerMapper to the scheduler. This requires a forward declaration in the runtime. To do this, we need to remove the template argument to the PointerMapper.

* Removed the template argument to the PointerMapper class.
* Added it to methods `SYCLMalloc()` and `get_buffer()` instead.
* The buffers saved in the PointerMapper are saved as `buffer_mem` and statically casted to templated buffers in `get_buffer()`.

2017-06-15 16:12 UTC, wyaneva commented on utils/vptr/include/virtual_ptr.hpp
>     */
TODO(Vanya): Remove "a pointer to" from the description.

2017-06-15 16:49 UTC, Ruyk requested changes
Some comments in the casting of the buffer

2017-06-15 16:49 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +//              cl::sycl::default_allocator<buffer_data_type> >
Can you remove the commented code?

2017-06-15 16:49 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +    buffer_t *b = static_cast<buffer_t *>(buf);
Can you not simply do this?

```
buffer_t retBuffer(reinterpret_cast<buffer_t>(get_node(ptr)->second._b))
```

2017-06-15 16:49 UTC, Ruyk commented on utils/vptr/include/virtual_ptr.hpp
> +    buffer_t *b = static_cast<buffer_t *>(buf);
Also, I don't think you need to pass the allocator type to the get_buffer if you use the typed allocator from the allocator headers of computecpp.

2017-06-16 14:39 UTC, wyaneva commented on utils/vptr/include/virtual_ptr.hpp
> +    buffer_t *b = static_cast<buffer_t *>(buf);
I have changed the code to use the copy constructor.

I have also removed the template argument for the allocator type.
However, to use the `typed_allocator`, I need to pass it an allocator type, so I still can't use it without one:
`template <typename T, typename AllocatorT>
class typed_allocator : public base_allocator {}`

Maybe we can use the `base_allocator` instead?

2017-06-16 14:40 UTC, wyaneva commented on utils/vptr/include/virtual_ptr.hpp
> +//              cl::sycl::default_allocator<buffer_data_type> >
Done: 17ea9e718e661f57e1773746954ceaf3509a1155

2017-06-19 09:53 UTC, Ruyk approved these changes

2017-06-19 09:54 UTC, merged

2017-06-19 09:54 UTC, Ruyk commented
Thanks for the changes!