Task #11628: Add get_accessor() methods
Ruyk/computecpp-sdk pull request #7
Opened 2017-06-20 14:07 UTC by wyaneva

2017-06-20 14:12 UTC, wyaneva commented
Hi @Ruyk, I have a couple of questions:

1. It seems to me that we need to keep the get_buffer() function as it is, as we need it in the get_accessor() functions -> we are effectively just calling get_access() on the buffers retrieved by get_buffer(). What do you think?
2. As get_access() is templated, then so should be get_accessor(). Is that correct?
3. The buffer object has two get_access() methods, one takes a command group handler. It is used in the tests. So I think we need an equivalent get_accessor() function. What do you think?

2017-06-28 16:25 UTC, Ruyk requested changes
On the get_access method you don't really need to call the get_buffer. Since you don't need the allocator type, you can directly call get_node and obtain the buffer, saving you from going through the casting of get_buffer.

2017-06-29 10:13 UTC, wyaneva commented
If I use get_node() to get the buffer, I only get a buffer_mem. But the accessor constructors require the child buffer<> type. So I still need to either cast (which is the same as just using get_buffer()) or add a new constructor for the accessors, which seems complicated.

Is there a particular reason we might not want to use get_buffer()? If we don't want it to be used at all, we could make it private?

2017-07-05 15:05 UTC, Ruyk approved these changes

2017-07-05 15:06 UTC, merged